plugins:
  - jekyll-sitemap

# SEO Stuff
author: Justin Croser
description: Justin Croser's personal webpage
lang: en
locale: en_GB
url: "https://justincroser.com"
git_web_base: https://github.com/justincroser/justincroser.github.io/blob/HEAD/
baseurl: ""
permalink: :title

# RSS feeds
feed:
  posts_limit: 20

# Netlify redirects
include:
  - _redirects
